### ISSUE TITLE
Changes to setup.py file

### ISSUE THREAD

**Issue by Williano** [urtzai/django-forum-app#3]
I get this error when i try to install the app 

ModuleNotFoundError: No module named 'pip.req'
 
So i fixed it with the solution below:

This is happening lately because of a change in pip 10.
The fix is pretty easy. You probably have something like:

from pip.req import parse_requirements

Change that to something like:

try: # for pip >= 10
    from pip._internal.req import parse_requirements
except ImportError: # for pip <= 9.0.3
    from pip.req import parse_requirements
That should do it

**Comment by urtzai** [comment]
Fixed with commit https://github.com/urtzai/django-forum-app/commit/2188e78f496531d74a635aa4806005d22963e30f
