### ISSUE TITLE
manage.py file is missing in the folder

### ISSUE THREAD

**Issue by anoopshrma** [urtzai/django-forum-app#4]
Please have a look at it!!

**Comment by urtzai** [comment]
Hi! @anoopshrma, this is a Django application, not a project itself. So you will need to create an entire Django project before you can add this app on it. The idea is to have a forum as a part of a website and not a website that is compound exclusively with a forum.

You can see an example here: https://gamerauntsia.eus/foroa/

So as you can see the Game Erauntsia forum is only a little part of the website.
